### ISSUE TITLE
Sample code for ASP.NET MVC5 OAuth

### ISSUE THREAD

**Issue by justabuzz** [ysinjab/InstagramCSharp#3]
Heya,

https://github.com/ysinjab/InstagramCSharp/blob/master/Samples/OAuth/ASP.net%20MVC5/InstagramOAuthController.cs#L35

Line 35 in the controller sample is:
`AuthUser authenticatedUser = JsonConvert.DeserializeObject<AuthUser>(responseContent);`

I believe it should be:
`AuthenticatedUser authenticatedUser = JsonConvert.DeserializeObject<AuthenticatedUser>(responseContent);`

Not a big issue for the lib itself, as this is sample code only, but would make it easier for whomever wants to use the sample for quick code that works.

Thanks for a great lib!

**Comment by ysinjab** [comment]
Many Thanks justabuzz ;)

I updated the samples
